Route createAVSPaymetnSubmission via SM
Layr-Labs/hello-world-avs pull request #92
Opened 2024-10-24 17:11 UTC by Sidu28

2024-10-28 13:40 UTC, stevennevins commented
there is some more updates that I think we need to make this more flexible.  
I started addressing some things in https://github.com/Layr-Labs/hello-world-avs/pull/93

we need to add a function with an initializer modifier on the service manager to initialize the owner and rewards updater state variables.  this makes it so you don't need to prank(address(0));

these values need to be read from a config file for the hello world deployment

And then we need to improve the core deployment library to set the rewards updater address on the RewardsCoordinator. We can't read this from the config json files in the core contract repo.  It looks like it's an address controlled by the person who wrote the script or maybe the pk for it is shared, but it's likely an internal address to eigenlayer and needs to be more configurable or a default anvil key

2024-10-28 15:41 UTC, Sidu28 commented
> there is some more updates that I think we need to make this more flexible. I started addressing some things in #93
> 
> we need to add a function with an initializer modifier on the service manager to initialize the owner and rewards updater state variables. this makes it so you don't need to prank(address(0));
> 
> these values need to be read from a config file for the hello world deployment
> 
> And then we need to improve the core deployment library to set the rewards updater address on the RewardsCoordinator. We can't read this from the config json files in the core contract repo. It looks like it's an address controlled by the person who wrote the script or maybe the pk for it is shared, but it's likely an internal address to eigenlayer and needs to be more configurable or a default anvil key

Makes sense.  Why do you think we can't make it readable from the config? Currently its just being hardcoded to 0 in the core deployment script

2024-10-28 15:48 UTC, Sidu28 commented
> there is some more updates that I think we need to make this more flexible. I started addressing some things in #93
> 
> we need to add a function with an initializer modifier on the service manager to initialize the owner and rewards updater state variables. this makes it so you don't need to prank(address(0));
> 
> these values need to be read from a config file for the hello world deployment
> 
> And then we need to improve the core deployment library to set the rewards updater address on the RewardsCoordinator. We can't read this from the config json files in the core contract repo. It looks like it's an address controlled by the person who wrote the script or maybe the pk for it is shared, but it's likely an internal address to eigenlayer and needs to be more configurable or a default anvil key

To make it more straightforward, should we just hardcode it in the CoreDeploymentLib.sol file to a default anvil key ourselves instead of using the config?

2024-11-06 17:19 UTC, stevennevins requested changes
Looks good! Can you add a step in the README that runs through after the contracts are deployed is able to go through the payment flow. I realize we missed that on the first pass for this feature

2024-12-26 02:10 UTC, Sidu28 commented
@stevennevins wanted to bump this for review

2025-01-17 22:59 UTC, stevennevins approved these changes

2025-01-18 01:41 UTC, merged